os: linux
dist: xenial
language: node_js
notifications:
    email:
        recipients:
            - kappelt.peter@gmail.com
        on_success: always
        on_failure: always
services:
    - docker
node_js:
    - '12'
branches:
  only:
    - dev
    - /^release-.*$/
    - /[\d]+\.[\d]+\.[\d]/
cache:
  directories:
    - node_modules
deploy:
    provider: releases
    body: Relase $VERSION
    skip_cleanup: true
    api_key: $GITHUB_DEPLOY_KEY
    file: exalicense-frontend-$VERSION.tar.gz
    draft: true
    on:
        tags: true
before_install:
    - export VERSION=$(cat VERSION)
    - npm update
    - cp public/config.sample.js public/config.js
install:
    - npm install
script:
    - npm run build
    - mv build exalicense-frontend
    - tar -czvf exalicense-frontend-$VERSION.tar.gz exalicense-frontend