os: linux
dist: xenial
language: node_js
notifications:
    email:
        recipients:
            - kappelt.peter@gmail.com
        on_success: always
        on_failure: always
services:
    - docker
node_js:
    - '12'
branches:
  only:
    - dev
    - /^release-.*$/
cache:
  directories:
    - node_modules
deploy:
    provider: releases
    body: Relase $VERSION
    api_key:
        secure: $GITHUB_DEPLOY_KEY
    file: exalicense-frontend-$VERSION.tar.gz
    on:
        branch: /^release-.*$/
before_install:
    - export VERSION=$(cat VERSION)
    - npm update
    - cp public/config.sample.js public/config.js
install:
    - npm install
script:
    - npm run build
    - tar -czvf exalicense-frontend-$VERSION.tar.gz build